from setuptools import setup, find_packages

setup(
    name="versa-speech-audio-toolkit",
    version="0.0.1",
    packages=find_packages(),
    install_requires=[
        "accelerate",
        "audioread",
        "ci-sdr",
        "Cython",
        "Distance",
        "editdistance",
        "einops",
        "espnet @ git+https://github.com/ftshijt/espnet.git@espnet_inference#egg=espnet",
        "espnet-tts-frontend",
        "fast-bss-eval",
        "fastdtw",
        "huggingface-hub",
        "hydra-core",
        "idna",
        "importlib-metadata",
        "kaggle",
        "kaldiio",
        "lazy_loader",
        "Levenshtein",
        "librosa",
        "mir-eval",
        "omegaconf",
        "onnxruntime",
        # NOTE(jiatong): use the latest commit for python 3.13
        "openai-whisper @ git+https://github.com/openai/whisper.git",
        "opt-einsum",
        "pesq",
        "protobuf",
        "pysptk",
        "pystoi",
        "python-dateutil",
        "pyworld",
        "pyyaml",
        "rapidfuzz",
        "resampy",
        "safetensors",
        "scikit-learn",
        "sentencepiece",
        "setuptools",
        "soundfile",
        "speechmos",
        "sympy",
        "threadpoolctl",
        "tokenizers",
        "torch",
        "torch-complex",
        "torchaudio",
        "torchlibrosa",
        "s3prl @ git+https://github.com/ftshijt/s3prl.git@numpy2#egg=s3prl",
        "transformers>=4.36.2",
        "espnet_model_zoo",
        "discrete-speech-metrics @ git+https://github.com/ftshijt/DiscreteSpeechMetrics.git@v1.0.2",
        "cdpam",
    ],
    extras_require={
        "dev": [
            "pytest>=6.0.0",
            "pytest-cov>=2.10.0",
            "black>=22.3.0",
            "flake8>=4.0.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "versa-score=versa.bin.scorer:main",
        ],
    },
    author="Jiatong Shi",
    author_email="ftshijt@gmail.com",
    description="A package for versatile evaluation of speech and audio",
    url="https://github.com/shinjiwlab/versa.git",
    keywords="speech metrics",
)
